### ISSUE TITLE
FEATURE: Implement Automatic Role Escalation Based on Assignment Completion

### ISSUE THREAD

**Issue by TjacksWebDev** [CodersCampus/cp#423]
# Implement Automatic Role Escalation Based on Assignment Completion

## Objective
To enhance the platform's user experience by implementing a function that escalates users from the "foundations" role to "full-stack" upon completion of certain assignments, thus eliminating the need for the "live-coding" option for role escalation. This aims to correct the current default behavior where users are not escalated appropriately based on their progress.

## Background
The current system defaults users to a "foundations /0" status unless the "live-coding" option is selected. This method has resulted in incorrect role assignment for users who have completed more advanced assignments (6-15) without opting for live-coding. With foundations students now participating in live-coding, reevaluating the necessity of a separate "foundations" role is essential.

## Tasks
- [ ] 1. **Review Current Role Assignment Logic**: Examine the existing system for assigning roles to identify necessary modifications for supporting automatic role escalation.
- [ ] 2. **Design Escalation Logic**: Create logic that evaluates a user's highest completed assignment number and automatically updates their role to "full-stack" if they have completed assignment 5 or beyond.
- [ ] 3. **Implement Automatic Escalation in Java**: Develop the function within the role and coding type assignment system to automatically adjust user roles. Sample Java code snippet:
    ```java
    public void updateUserRole(User user) {
        int maxCompletedAssignment = Collections.max(user.getCompletedAssignments());
        if (maxCompletedAssignment >= 5) {
            user.setRole("full-stack");
            // Assume updateUser is a method that updates the user's role in the database
            database.updateUser(user);
        }
    }
    ```
- [ ] 4. **Update Database for Role Changes**: Ensure the database accurately reflects the updated role status for users automatically escalated.
- [ ] 5. **Comprehensive Testing**: Conduct thorough testing to verify that the function correctly escalates users based on their assignment completion status.
- [ ] 6. **Documentation Revision**: Update the system documentation to accurately represent the new role assignment logic and its operational parameters.

## Done
- Automatic update of user roles from "foundations" to "full-stack" based on the highest completed assignment, without needing the live-coding option.
- Users who complete assignment 5 or beyond are accurately escalated to the "full-stack" role.
- Updated system documentation that reflects the new role assignment mechanism.
```
