### ISSUE TITLE
CORE: Set up Spring Profiles

### ISSUE THREAD

**Issue by davenaugler** [CodersCampus/cp#426]
# CORE: Set up Spring Profiles #426

## Objective

The objective of this ticket is to integrate Spring profiles into the project, as outlined in Coders Campus Unit 13 Lesson 9. This involves setting up configurations for `Local H2` and `Local MySQL` databases to facilitate different development and testing scenarios. Following the successful implementation of Spring profiles, the next step is to update the relationship types in the "Children of Student Module," as detailed in the related issue [#419](https://github.com/your-repository-here/issues/419).

## Tasks

1. **Research and Documentation**
   - Review Spring documentation on profiles to understand best practices for configuration.
   - Document the steps required for setting up Spring profiles in the project's README or relevant documentation files.

2. **Implementation**
   - Create two new Spring profiles: `local-h2` and `local-mysql`.
   - Configure the `application.properties` files to include settings specific to each profile.

### `local-h2` Profile Configuration

Add the following properties to your `application-local-h2.properties` file to set up the H2 database:

```properties
# Spring profile
spring.profiles.active=local-h2

# Datasource configuration
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
```

### `local-mysql` Profile Configuration

Add the following properties to your `application-local-mysql.properties` file for the MySQL database setup:

```properties
# Spring profile
spring.profiles.active=local-mysql

# Datasource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/yourDatabase?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=yourUsername
spring.datasource.password=yourPassword

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update
```

3. **Testing**
   - Test the application startup and basic functionality with each profile to ensure the configurations are correctly applied.
   - Verify that the application can connect to each database type without issues and perform basic CRUD operations.
   - See below comment for tests.

4. **Update Relationships in Children of Student Module**
   - Refer to issue [#419](https://github.com/your-repository-here/issues/419) for details on the required relationship updates.
   - Ensure that changes made to the relationships are compatible with both the `local-h2` and `local-mysql` profiles.

## Completion Criteria

- [ ] Spring profiles for `local-h2` and `local-mysql` are correctly configured and documented.
- [ ] The application can be seamlessly switched between the two profiles without errors.
- [ ] All tests pass with both profiles active, verifying the application's functionality with each database configuration.
- [ ] The relationship updates in the "Children of Student Module" are completed and tested, ensuring compatibility with both database profiles.
```
